install.packages("ISLR")

install.packages("ISLR2")
install.packages("car")
install.packages("rmarkdown")
install.packages("knitr")
install.packages("ggpubr")
install.packages("ggplot2")
install.packages("GGally")
install.packages("kableExtra")
install.packages("dplyr")
install.packages("class")
install.packages("ROCR")
install.packages("pROC")
install.packages("boot")
install.packages("leaps")
install.packages("glmnet")
install.packages("gam")
install.packages("tree")
install.packages("randomForest")
install.packages("akima")
install.packages("gbm")
install.packages("pls")
install.packages("splines")
install.packages("e1071")
install.packages("caret")
install.packages("DAAG")

install.packages("formatR")
install.packages("ggstance")
install.packages("ggformula")
install.packages("mosaicData")
install.packages("usdm")
install.packages("sensitivity")
install.packages("factoextra")
install.packages("colorspace")
install.packages("dendextend")
install.packages("gplot")

install.packages("jtools")

install.packages("mplot")